Create schema term2;
USE term2;

CREATE TABLE IF NOT EXISTS e3(
   INDIC_DE_Labels                                         VARCHAR(65) NOT NULL PRIMARY KEY
  ,Average_population_total                                VARCHAR(11) NOT NULL
  ,Net_migration_plus_statistical_adjustment               VARCHAR(9) NOT NULL
  ,Crude_rate_of_net_migration_plus_statistical_adjustment VARCHAR(5) NOT NULL
  ,Deaths_total                                            VARCHAR(9) NOT NULL
  ,Average_population_females                              VARCHAR(11) NOT NULL
);
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('European Union - 27 countries (from 2020)','447,022,255','1,410,329','3.2','4,653,033','228,615,324');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('European Union - 28 countries (2013-2020)','513,858,582','1,680,681','3.3','5,257,654',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Euro area - 19 countries  (from 2015)','342,105,847','1,261,181','3.7','3,438,580','174,909,656');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Euro area - 18 countries (2014)','339,311,710','1,250,387','3.7','3,400,299','173,415,491');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Belgium','11,488,980','58,009','5','108,783','5,825,954');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Bulgaria','6,975,761','-2,012','-0.3','108,083','3,593,087');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Czechia','10,671,870','44,270','4.1','112,362','5,413,775');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Denmark','5,814,422','9,473','1.6','53,958','2,921,427');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Germany (until 1990 former territory of the FRG)','83,092,962','308,928','3.7','939,520','42,090,810');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Germany including former GDR','83,092,962','308,928','3.7','939,520','42,090,810');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Estonia','1,326,898','5,458','4.1','15,401','699,442');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Ireland','4,934,340','31,870','6.5','30,959','2,491,071');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Greece','10,721,582','35,168','3.3','124,965','5,509,692');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Spain','47,134,837','452,909','9.6','416,102','24,030,551');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('France','67,388,001','54,440','0.8','613,388','34,791,715');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('France (metropolitan)',':',':',':',':',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Croatia','4,067,206','-2,422','-0.6','51,794','2,095,095');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Italy','59,729,081','39,148','0.7','634,417','30,638,435');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Cyprus','881,952','8,797','10','6,239','450,801');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Latvia','1,913,822','-3,360','-1.8','27,719','1,030,889');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Lithuania','2,794,137','10,794','3.9','38,281','1,494,165');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Luxembourg','620,001','10,267','16.6','4,283','308,159');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Hungary','9,771,141','33,562','3.4','129,892','5,092,836');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Malta','504,062','20,343','40.4','3,688','245,263');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Netherlands','17,344,874','107,627','6.2','151,885','8,730,316');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Austria','8,879,920','40,723','4.6','83,386','4,512,017');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Poland','37,965,475','20,081','0.5','409,709','19,588,597');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Portugal','10,286,263','44,506','4.3','111,793','5,430,092');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Romania','19,371,648','-25,451','-1.3','259,889','9,891,093');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Slovenia','2,088,385','16,213','7.8','20,588','1,043,524');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Slovakia','5,454,147','3,632','0.7','53,234','2,790,934');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Finland','5,521,606','15,709','2.8','53,949','2,795,830');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Sweden','10,278,887','71,647','7','88,766','5,109,761');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('European Economic Area (EU28 - 2013-2020 and IS, LI, NO)','519,605,603','1,711,480','3.3','5,300,876',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('European Free Trade Association','14,322,301','73,913','5.2','111,002','7,169,483');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Iceland','360,563','4,966','13.8','2,275','175,674');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Liechtenstein','38,563','276','7.2','263','19,443');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Norway','5,347,896','25,557','4.8','40,684','2,652,079');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Switzerland','8,575,280','43,114','5','67,780','4,322,288');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('United Kingdom','66,836,327','270,352','4','604,621',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Montenegro','622,028','-937','-1.5','6,595','314,394');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('North Macedonia','2,076,694','-276','-0.1','20,446','1,036,736');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Albania','2,854,191','-23,096','-8.1','21,937','1,429,088');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Serbia','6,945,235','0','0','101,458','3,561,510');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Türkiye','82,579,440','403,404','4.9','435,941','41,148,882');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Andorra','76,860','1,128','14.7','301',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Belarus','9,441,762','-33,956','-3.6','120,470',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Bosnia and Herzegovina',':',':',':',':',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Kosovo (under United Nations Security Council Resolution 1244/99)','1,788,891','-25,919','-14.5','9,430','908,744');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Moldova','2,663,251','-41,232','-15.5','36,416',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Monaco',':',':',':',':',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Russia',':',':',':',':',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('San Marino','34,663','164','4.7','251',':');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Ukraine','41,858,172','21,512','0.5','581,114','22,458,816');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Armenia','2,962,482','-15,430','-5.2','26,186','1,563,114');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Azerbaijan','10,024,283','388','0','55,916','5,019,077');
INSERT INTO e3(INDIC_DE_Labels,Average_population_total,Net_migration_plus_statistical_adjustment,Crude_rate_of_net_migration_plus_statistical_adjustment,Deaths_total,Average_population_females) VALUES ('Georgia','3,720,161','-8,243','-2.2','46,659','1,929,572');
