rm(list=ls())
#SentimentAnalysis and tidyverse packages (the latter for data wrangling) must be installed first
library(SentimentAnalysis)
library(tidyverse)

#Importing original .csv containing the Dialogues: each block of text assigned to a character in a row
import <- read.csv('C:/Users/Gabi/Downloads/Harry_Potter_Movies/Dialogue.csv')

#Applying sentiment analysis, selecting the required column (the result is anotehr dataframe)
import$sent.score <- analyzeSentiment(import$Dialogue) %>%  select('SentimentGI')

#Creating another column that converts the sentiment score into 3 factors: positive, neutral and negative
import$sent.value <- convertToDirection(analyzeSentiment(import$Dialogue)) %>%  select('SentimentGI')

#'analyseSentiment' function produces another dataframe, which is now nested in the original df. Unnesting:
import <- unnest(import,cols = c(sent.score, sent.value), names_repair = "minimal")

#The result of the unnest is two identically named 'SentimentGI' columns, as they were part of different dataframe subsets
colnames(import)[6:7] = c("sent_score","sent_value")

#Extra formatting
import$sent_score <- round(import$sent_score, digit = 2)
import$sent_score[is.nan(import$sent_score)]<- 0
import$sent_value[is.na(import$sent_value)] <- "neutral"

#Exporting to .csv while making sure that the index column generated by R Studio does not get exported
write.csv(import,'Dialogues_sentiment.csv', row.names = FALSE)
